Before fixing execution from Vim

diff --git a/knit b/knit
--- a/knit
+++ b/knit
@@ -1,45 +1,68 @@
 #!/usr/bin/env bash
 
-Rmd=$PWD/$1
-indir=`dirname $Rmd`
-postname=`basename $1 .Rmd`
-md="$indir/$postname.md"
-rscript=$HOME/src/myknit.R 
+# input args
+Rmdpath=$1
 jekylldir=${2:-$HOME/test/jekyll/test14}
-category=$3
-postdir=$jekylldir/$category/_posts
-postmd="$postdir/$postname.md"
-relRfigs=assets/R-figures
-absRfigs=$jekylldir/$relRfigs
-relfigdir=$relRfigs/$postname
-absfigdir=$absRfigs/$postname
+relprojectdir=$3
 
+# this generates an .md in the directory of the input .Rmd
+knitrscript=$HOME/src/myknit.R 
+
+# directory of input .Rmd; this will hold intermediate dirs and files
+postname=`basename $Rmdpath .Rmd`
+indir=`dirname $Rmdpath`
+cd $indir || { echo "`basename $0`: could not locate directory $indir" 1>&2; exit 1; }
+tmpdir=`mktemp -dp .` && cd $tmpdir
+Rmd="../$postname.Rmd"
+md="../$postname.md"
+
+# make output directories if necessary
+projectdir=$jekylldir/$relprojectdir
+test -d $projectdir || { echo "`basename $0`: could not locate directory $projectdir" 1>&2; exit 1; }
+
+
+# function that integrates newly generated .md and figures into jekyll site
 post2jekyll () {
-    md=$1 postmd=$2 absfigdir=$3 relfigdir=$4
-    Rmddir=`dirname $md`
+    md=$1 jekylldir=$2 relprojectdir=$3
+
+    # set up paths and variables, ensure that dirs exist
+    absprojectdir=$jekylldir/$relprojectdir
+    postname=`basename $md .md`
+    if test -z $relprojectdir; then
+        relRdir=R/$postname
+    else
+        relRdir=$relprojectdir/R/$postname
+    fi
+    # absolute path to R-related or R-generated files and directories (e.g. .Rmd, 'figure')
+    absRdir=$absprojectdir/R/$postname
+    test -d $absRdir || mkdir -p $absRdir
+
+    # subdirectory for figures with $absRdir
+    relRfigdir=$relRdir/figure
+    absRfigdir=$jekylldir/$relRfigdir
+    # replace absRfigdir with the newly generated figure (if present)
+    test -d $absRfigdir && rm -rf $absRfigdir
+    if test -d figure; then
+        mv figure $absRfigdir
+        (cd `dirname $md` && rm -rf figure && ln -s $absRfigdir figure)
+    fi
+
+    # prepare and give the .md post to jekyll
+    abspostdir=$absprojectdir/_posts
+    test -d $abspostdir || mkdir -p $abspostdir
+    postmd=$abspostdir/$postname.md
     mv -f $md $postmd
-    prefix="{{ site.baseurl }}/$relfigdir"
     # hack .md to fix its links to images
+    prefix="{{ site.baseurl }}/$relRfigdir"
     sed -i "/plot of chunk/ s:figure:$prefix:" $postmd
     echo '<!-- MathJax scripts -->' >> $postmd
     echo '<script type="text/javascript" src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>' >> $postmd
     # write protection to emphasize that $postmd is generated by a script and not to be edited manually
     chmod -w $postmd
-    test -d $absfigdir && rm -rf $absfigdir
-    mv figure $absfigdir
-    cd $Rmddir
-    rm -rf figure && ln -s $absfigdir figure
 }
 
-# make output directories if necessary
-test -d $postdir || mkdir -p $postdir
-test -d $absRfigs || mkdir -p $absRfigs
-tmpdir=`mktemp -d`
-cd $tmpdir
-#test -e figure && rm -rf figure
-
 # knit the .Rmd to .md
-if Rscript $rscript $Rmd && post2jekyll $md $postmd $absfigdir $relfigdir; then
+if Rscript $knitrscript $Rmd && post2jekyll $md $jekylldir $relprojectdir; then
     rm -rf $tmpdir
     cd $jekylldir && bundle exec jekyll build --incremental
 else
