knit largely completed

diff --git a/knit b/knit
--- a/knit
+++ b/knit
@@ -1,9 +1,44 @@
 #!/usr/bin/env bash
 
+if test $# -ne 3; then
+    cat <<EOF
+Usage:
+`basename $0` [path/to/]post-name.Rmd jekyll/dir project/dir
+`basename $0` [path/to/]post-name.Rmd jekyll/dir -
+
+Use knitrscript ~/src/myknit.R to knit post-name.Rmd into post-name.md,
+then integrate post-name.md into the jekyll site...
+    under jekyll/dir/project/dir (first form of usage)
+    or
+    under jekyll/dir (second form of usage when the last argument is '-').
+
+Output:
+1. jekyll/dir/[project/dir/]_posts/post-name.md
+2. jekyll/dir/[project/dir/]R/post-name/post-name.Rmd
+3. jekyll/dir/[project/dir/]R/post-name/figure/*
+
+Details:
+Integration into the jekyll site means more than merely placing the output files
+(post-name.md and figures) into specific subdirectories under jekyll/dir.
+To work with jekyll, some essential modifications to the markup of post-name.md
+are carried out:
+1. fix the relative url of the 'figure' directory in the src attribute of
+    <img> tags (old url: figure; new url: prefix="{{ site.baseurl }}/$relRfigdir")
+2. add a <script> tag for MathJax support
+
+Additionally, a symbolic link to jekyll/dir/[project/dir/]R/post-name/figure/
+is created in the input directory (path/to in path/to/post-name.Rmd).
+EOF
+exit
+fi
+
 # input args
 Rmdpath=$1
-jekylldir=${2:-$HOME/test/jekyll/test14}
-relprojectdir=$3
+jekylldir=$2
+case $3 in
+    -) relprojectdir='';;
+    *) relprojectdir=$3;;
+esac
 
 # this generates an .md in the directory of the input .Rmd
 knitrscript=$HOME/src/myknit.R 
@@ -12,9 +47,11 @@ knitrscript=$HOME/src/myknit.R
 postname=`basename $Rmdpath .Rmd`
 indir=`dirname $Rmdpath`
 cd $indir || { echo "`basename $0`: could not locate directory $indir" 1>&2; exit 1; }
-tmpdir=`mktemp -dp .` && cd $tmpdir
-Rmd="../$postname.Rmd"
-md="../$postname.md"
+# figure is a symlink if the script has already been run successfully;
+# otherwise could be a directory; in any case, it will be automatically removed!
+rm -rf figure
+Rmd="$postname.Rmd"
+md="$postname.md"
 
 # make output directories if necessary
 projectdir=$jekylldir/$relprojectdir
@@ -23,7 +60,7 @@ test -d $projectdir || { echo "`basename $0`: could not locate directory $projec
 
 # function that integrates newly generated .md and figures into jekyll site
 post2jekyll () {
-    md=$1 jekylldir=$2 relprojectdir=$3
+    md=$1 jekylldir=$2 relprojectdir=$3 Rmd=$4
 
     # set up paths and variables, ensure that dirs exist
     absprojectdir=$jekylldir/$relprojectdir
@@ -36,6 +73,7 @@ post2jekyll () {
     # absolute path to R-related or R-generated files and directories (e.g. .Rmd, 'figure')
     absRdir=$absprojectdir/R/$postname
     test -d $absRdir || mkdir -p $absRdir
+    cp $Rmd -t $absRdir
 
     # subdirectory for figures with $absRdir
     relRfigdir=$relRdir/figure
@@ -44,7 +82,7 @@ post2jekyll () {
     test -d $absRfigdir && rm -rf $absRfigdir
     if test -d figure; then
         mv figure $absRfigdir
-        (cd `dirname $md` && rm -rf figure && ln -s $absRfigdir figure)
+        ln -s $absRfigdir figure
     fi
 
     # prepare and give the .md post to jekyll
@@ -62,10 +100,9 @@ post2jekyll () {
 }
 
 # knit the .Rmd to .md
-if Rscript $knitrscript $Rmd && post2jekyll $md $jekylldir $relprojectdir; then
-    rm -rf $tmpdir
+if Rscript $knitrscript $Rmd && post2jekyll $md $jekylldir $relprojectdir $Rmd; then
     cd $jekylldir && bundle exec jekyll build --incremental
 else
-    echo "`basename $0`: error; check $tmpdir for intermediate files" 1>&2
+    echo "`basename $0`: error; check $indir for intermediate files" 1>&2
     exit 1
 fi
